id: module-03-channels
title: "The Channel System"
description: "How OpenClaw connects to messaging platforms — architecture, Telegram, WhatsApp, Discord, Slack, and the broader channel ecosystem."
order: 3
icon: "📨"
quiz_file: quiz.yaml
lessons:
  - slug: channel-plugin-architecture
    title: "Channel Plugin Architecture"
    file: 01-channel-plugin-architecture.md
    duration_min: 12
  - slug: telegram-and-whatsapp
    title: "Telegram and WhatsApp"
    file: 02-telegram-whatsapp.md
    duration_min: 15
  - slug: discord-slack-others
    title: "Discord, Slack, and Other Channels"
    file: 03-discord-slack-others.md
    duration_min: 12
