id: module-09-deployment
title: "Deployment Patterns"
description: "How to run OpenClaw reliably — macOS LaunchAgent, Docker Compose, Linux VPS with systemd, HTTPS reverse proxy, and Tailscale remote access."
order: 9
icon: "🚀"
quiz_file: quiz.yaml
lessons:
  - slug: macos-deployment
    title: "macOS Deployment"
    file: 01-macos-deployment.md
    duration_min: 12
  - slug: docker-deployment
    title: "Docker Deployment"
    file: 02-docker-deployment.md
    duration_min: 15
  - slug: linux-vps-deployment
    title: "Linux VPS Deployment"
    file: 03-linux-vps.md
    duration_min: 15
